# =============================================
# Configuracin de Base de Datos MySQL
# =============================================
db.host=localhost
db.port=3306
db.name=crud_usuario
db.username=root
db.password=199rafaelxz

# =============================================
# Configuraci�n SMTP (JavaMail)
# =============================================
smtp.host=smtp.gmail.com
smtp.port=465
smtp.username=rafael
smtp.password=sdjd gyis wfyw xdoa
smtp.from.address=rafaelenriquext@gmail.com
smtp.from.name=Gestin de Usuarios

